/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PipelineTarget = "Desktop" | "Gamemode";
export type SelectionFor_String =
  | {
      type: "Action";
      value: Action;
    }
  | {
      type: "OneOf";
      value: {
        actions: string[];
        selection: string;
      };
    }
  | {
      type: "AllOf";
      value: string[];
    };
export type Action =
  | {
      type: "DesktopSessionHandler";
      value: DesktopSessionHandler;
    }
  | {
      type: "DisplayConfig";
      value: DisplayConfig;
    }
  | {
      type: "VirtualScreen";
      value: VirtualScreen;
    }
  | {
      type: "MultiWindow";
      value: MultiWindow;
    }
  | {
      type: "CitraLayout";
      value: CitraLayout;
    }
  | {
      type: "CemuLayout";
      value: CemuLayout;
    }
  | {
      type: "MelonDSLayout";
      value: MelonDSLayout;
    }
  | {
      type: "SourceFile";
      value: SourceFile;
    };
export type RelativeLocation = "Above" | "Below" | "LeftOf" | "RightOf" | "SameAs";
export type ExternalDisplaySettings =
  | {
      type: "Previous";
    }
  | {
      type: "Native";
    }
  | {
      type: "Preference";
      value: ModePreference;
    };
export type AspectRatioOption =
  | ("Any" | "Native")
  | {
      Exact: number;
    };
export type ModeOptionForDouble =
  | {
      Exact: number;
    }
  | {
      AtLeast: number;
    }
  | {
      AtMost: number;
    };
export type ModeOptionFor_Resolution =
  | {
      Exact: Resolution;
    }
  | {
      AtLeast: Resolution;
    }
  | {
      AtMost: Resolution;
    };
export type MultiWindowLayout = "column-right" | "column-left" | "square-right" | "square-left" | "separate";
export type LimitedMultiWindowLayout = "column-right" | "column-left" | "square-right" | "square-left";
export type CitraLayoutOption =
  | {
      type: "Default";
    }
  | {
      type: "SingleScreen";
    }
  | {
      type: "LargeScreen";
    }
  | {
      type: "SideBySide";
    }
  | {
      type: "SeparateWindows";
    }
  | {
      type: "HybridScreen";
    }
  | {
      type: "Unknown";
      value: number;
    };
/**
 * melonDS layout options. Because of the "unique" way melonDS handles layouts, these options do not map 1:1.
 */
export type MelonDSLayoutOption = "Natural" | "Vertical" | "Horizontal" | "Hybrid" | "Single";
export type MelonDSSizingOption = "Even" | "EmphasizeTop" | "EmphasizeBottom" | "Auto";
export type FileSource =
  | {
      type: "Flatpak";
      value: FlatpakSource;
    }
  | {
      type: "AppImage";
      value: AppImageSource;
    }
  | {
      type: "EmuDeck";
      value: EmuDeckSource;
    }
  | {
      type: "Custom";
      value: CustomFileOptions;
    };
export type FlatpakSource = "Cemu" | "Citra" | "MelonDS";
export type AppImageSource = "Cemu";
export type EmuDeckSource = "CemuProton";
export type DependencyError =
  | {
      type: "SystemCmdNotFound";
      value: string;
    }
  | {
      type: "PathIsNotFile";
      value: string;
    }
  | {
      type: "PathIsNotDir";
      value: string;
    }
  | {
      type: "PathNotFound";
      value: string;
    }
  | {
      type: "KwinScriptNotFound";
      value: string;
    }
  | {
      type: "KwinScriptFailedInstall";
      value: string;
    }
  | {
      type: "FieldNotSet";
      value: string;
    };
export type SelectionFor_PipelineAction =
  | {
      type: "Action";
      value: Action;
    }
  | {
      type: "OneOf";
      value: {
        actions: PipelineAction[];
        selection: string;
      };
    }
  | {
      type: "AllOf";
      value: PipelineAction[];
    };

/**
 * Marker type for generating API json schema types for ts
 */
export interface Api {
  autostart_request: AutoStartRequest;
  create_profile_request: CreateProfileRequest;
  create_profile_response: CreateProfileResponse;
  delete_profile_request: DeleteProfileRequest;
  get_app_profile_request: GetAppProfileRequest;
  get_app_profile_response: GetAppProfileResponse;
  get_default_app_override_for_profile_request: GetDefaultAppOverrideForProfileRequest;
  get_default_app_override_for_profile_response: GetDefaultAppOverrideForProfileResponse;
  get_profile_request: GetProfileRequest;
  get_profile_response: GetProfileResponse;
  get_profiles_response: GetProfilesResponse;
  get_settings_response: GetSettingsResponse;
  get_templates_response: GetTemplatesResponse;
  reify_pipeline_request: ReifyPipelineRequest;
  reify_pipeline_response: ReifyPipelineResponse;
  set_app_profile_override_request: SetAppProfileOverrideRequest;
  set_app_profile_settings_request: SetAppProfileSettingsRequest;
  set_profile_request: SetProfileRequest;
  set_settings_request: SetSettingsRequest;
}
export interface AutoStartRequest {
  app_id: string;
  game_id?: string | null;
  profile_id: string;
  target: PipelineTarget;
}
export interface CreateProfileRequest {
  pipeline: PipelineDefinition;
}
export interface PipelineDefinition {
  actions: PipelineActionLookup;
  description: string;
  id: string;
  name: string;
  primary_target_override?: PipelineTarget | null;
  register_exit_hooks: boolean;
  source_template: TemplateInfo;
  targets: {
    [k: string]: string[];
  };
}
export interface PipelineActionLookup {
  actions: {
    [k: string]: PipelineActionSettings;
  };
}
export interface PipelineActionSettings {
  /**
   * Flags whether the selection is enabled. If None, not optional. If Some(true), optional and enabled, else disabled.
   */
  enabled?: boolean | null;
  /**
   * Whether or not the pipeline action is hidden on the QAM
   */
  is_visible_on_qam: boolean;
  /**
   * Flags whether the selection is overridden by the setting from a different profile.
   */
  profile_override?: string | null;
  /**
   * The value of the pipeline action
   */
  selection: SelectionFor_String;
}
export interface DesktopSessionHandler {
  deck_is_primary_display: boolean;
  id: string;
  teardown_deck_location?: RelativeLocation | null;
  teardown_external_settings: ExternalDisplaySettings;
}
export interface ModePreference {
  aspect_ratio: AspectRatioOption;
  refresh: ModeOptionForDouble;
  resolution: ModeOptionFor_Resolution;
}
export interface Resolution {
  h: number;
  w: number;
}
export interface DisplayConfig {
  deck_is_primary_display: boolean;
  deck_location?: RelativeLocation | null;
  external_display_settings: ExternalDisplaySettings;
  id: string;
}
export interface VirtualScreen {
  id: string;
}
export interface MultiWindow {
  /**
   * Some(options) if Cemu is configurable, None otherwise
   */
  cemu?: CemuOptions | null;
  /**
   * Some(options) if Citra is configurable, None otherwise
   */
  citra?: CitraOptions | null;
  /**
   * Some(options) if Dolphin is configurable, None otherwise
   */
  dolphin?: DolphinOptions | null;
  general: GeneralOptions;
  id: string;
}
export interface CemuOptions {
  multi_screen_layout: MultiWindowLayout;
  single_screen_layout: LimitedMultiWindowLayout;
}
export interface CitraOptions {
  multi_screen_layout: MultiWindowLayout;
  single_screen_layout: LimitedMultiWindowLayout;
}
export interface DolphinOptions {
  gba_blacklist: number[];
  multi_screen_multi_secondary_layout: MultiWindowLayout;
  multi_screen_single_secondary_layout: MultiWindowLayout;
  single_screen_layout: LimitedMultiWindowLayout;
}
export interface GeneralOptions {
  keep_above: boolean;
  swap_screens: boolean;
}
export interface CitraLayout {
  id: string;
  layout: CitraLayoutState;
}
export interface CitraLayoutState {
  fullscreen: boolean;
  layout_option: CitraLayoutOption;
  swap_screens: boolean;
}
export interface CemuLayout {
  id: string;
  layout: CemuLayoutState;
}
export interface CemuLayoutState {
  fullscreen: boolean;
  separate_gamepad_view: boolean;
}
export interface MelonDSLayout {
  book_mode: boolean;
  id: string;
  layout_option: MelonDSLayoutOption;
  sizing_option: MelonDSSizingOption;
  swap_screens: boolean;
}
export interface SourceFile {
  id: string;
  source: FileSource;
}
export interface CustomFileOptions {
  /**
   * user defined custom path
   */
  path?: string | null;
  /**
   * valid file extensions for source file
   */
  valid_ext: string[];
}
export interface TemplateInfo {
  id: string;
  /**
   * The template's version; should be updated each time an action is moved, added, or removed
   */
  version: number;
}
export interface CreateProfileResponse {
  profile_id: string;
}
export interface DeleteProfileRequest {
  profile: string;
}
export interface GetAppProfileRequest {
  app_id: string;
}
export interface GetAppProfileResponse {
  app: AppProfile;
}
export interface AppProfile {
  default_profile?: string | null;
  id: string;
  overrides: {
    [k: string]: PipelineDefinition;
  };
}
export interface GetDefaultAppOverrideForProfileRequest {
  profile_id: string;
}
export interface GetDefaultAppOverrideForProfileResponse {
  pipeline?: PipelineDefinition | null;
}
export interface GetProfileRequest {
  profile_id: string;
}
export interface GetProfileResponse {
  profile?: CategoryProfile | null;
}
export interface CategoryProfile {
  id: string;
  pipeline: PipelineDefinition;
  tags: string[];
}
export interface GetProfilesResponse {
  profiles: CategoryProfile[];
}
export interface GetSettingsResponse {
  global_settings: GlobalConfig;
}
export interface GlobalConfig {
  display_restoration: DesktopSessionHandler;
  /**
   * If true, inject buttons onto app action bar
   */
  enable_ui_inject: boolean;
  /**
   * If `enable_ui_inject` is true, set the "Play" button to this target
   */
  primary_ui_target: PipelineTarget;
  restore_displays_if_not_executing_pipeline: boolean;
}
export interface GetTemplatesResponse {
  templates: Template[];
}
export interface Template {
  id: string;
  pipeline: PipelineDefinition;
  /**
   * The template's version; should be updated each time an action is moved, added, or removed
   */
  version: number;
}
export interface ReifyPipelineRequest {
  pipeline: PipelineDefinition;
}
export interface ReifyPipelineResponse {
  config_errors: {
    [k: string]: DependencyError[];
  };
  pipeline: Pipeline;
}
export interface Pipeline {
  description: string;
  name: string;
  primary_target_override?: PipelineTarget | null;
  register_exit_hooks: boolean;
  targets: {
    [k: string]: SelectionFor_PipelineAction;
  };
}
export interface PipelineAction {
  description?: string | null;
  /**
   * Flags whether the selection is enabled. If None, not optional. If Some(true), optional and enabled, else disabled.
   */
  enabled?: boolean | null;
  id: string;
  /**
   * Whether or not the pipeline action is hidden on the QAM
   */
  is_visible_on_qam: boolean;
  name: string;
  /**
   * Flags whether the selection is overridden by the setting from a different profile.
   */
  profile_override?: string | null;
  /**
   * The value of the pipeline action
   */
  selection: SelectionFor_PipelineAction;
}
export interface SetAppProfileOverrideRequest {
  app_id: string;
  pipeline: PipelineDefinition;
  profile_id: string;
}
export interface SetAppProfileSettingsRequest {
  app_id: string;
  default_profile?: string | null;
}
export interface SetProfileRequest {
  profile: CategoryProfile;
}
export interface SetSettingsRequest {
  global_settings: GlobalConfig;
}
